basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=225, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.jpeg')
    slug = models.SlugField(max_length=225)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from store.models import Product
from .basket import Basket

# Create your views here.


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response

def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# Create your views here.


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}MyBookStore{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
    integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous">
  </script>
</head>

<body>
  <header class="p-3 text-bg-dark">
    <div class="container-fluid">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="text-light text-decoration-none">
          <h1><strong>MyBookStore</strong></h1>
        </a>

        <ul class="nav col-12 col-lg-auto ms-4 me-lg-auto mb-2 justify-content-center mb-md-0">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle px-2 text-light" id="navbarDropdown" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Library
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

              <li><a class="dropdown-item" href="{% url 'store:product_all' %}">All</a></li>

              {% for c in categories %}

              <li>
                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
              </li>

              {% endfor %}
            </ul>
          </li>
          <li><a href="#" class="nav-link px-2 text-light">FAQs</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..."
            aria-label="Search" />
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">
            Login
          </button>
          <button type="button" class="btn btn-primary me-2">Sign-up</button>
        </div>

        <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-outline-light ms-1">

          {% with total_qty=basket|length %}
            <div id="basket-qty" class="d-inline-flex">
              {% if total_qty > 0 %}
                {{ total_qty }}
              {% else %}
                0
              {% endif %}
            </div>
          {% endwith %}

          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-bag-check mb-1" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
              d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
            <path
              d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z" />
          </svg>
          Basket
        </a>
      </div>
    </div>
  </header>
  <div id="content">{% block content %} {% endblock %}</div>
</body>

</html>

templates/store/basket/summary.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Basket Summary{% endblock%}

{% block content %}

<main class="pt-5">
    <div class="container">
        <h1 class="h5">Shopping Basket</h1>
        {% for item in basket %}
        {% with product=item.product %}
        <div data-index="{{product.id}}" class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image"
                    src="{{ product.image.url }}">
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">{{ product.title }}</h1>
                </a>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Paperback Book</div>
                            <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-12">
                                <label for="select">Qty</label>
                                <select id="select{{product.id}}">
                                    <option selected>
                                        {{item.qty}}
                                    </option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                                <button type="button" id="update-button" data-index="{{product.id}}"
                                    class="btn btn-outline-secondary btn-sm update-button">
                                    Update
                                </button>
                                <button type="button" id="delete-button" data-index="{{product.id}}"
                                    class="btn btn-outline-secondary btn-sm delete-button">
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
        <div class="col-12 text-end">
            <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
        </div>
    </div>
</main>

<script>
    // Delete item
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
            $('.product-item[data-index="'+ prodid +'"]').remove();
            document.getElementById("basket-qty").innerHTML = json.qty;
            document.getElementById("subtotal").innerHTML = json.subtotal;
        },
        error: function (xhr, errmsg, err) {}
      });
    })

    // Update item
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_update" %}',
          data: {
            productid: $(this).data('index'),
            productqty: $('#select' + prodid + ' option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
          },
          success: function (json) {
            document.getElementById("basket-qty").innerHTML = json.qty;
            document.getElementById("subtotal").innerHTML = json.subtotal;
          },
          error: function (xhr, errmsg, err) {}
        });
      })
  </script>

{% endblock content %}

templates/store/home.html
{% extends './base.html' %}
{% load static %}
{% block title %}MyBookStore{% endblock%}
{% block content %}

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-bold">Search, Read, Buy, Review</h1>
        <p class="lead text-muted">
          Something short and leading about the collection below—its contents,
          the creator, etc. Make it short and sweet, but not too short so folks
          don’t simply skip over it entirely.
        </p>
        <p>
          <a href="#" class="btn btn-primary my-2">Make an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img
              class="img-fluid"
              alt="Responsive image"
              src="{{ product.image.url }}"
            />
            <div class="card-body">
              <p class="card-text">
                <a
                  class="text-dark text-decoration-none"
                  href="{{ product.get_absolute_url }}"
                  >{{ product.title }}</a
                >
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/store/products/category.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Home{% endblock%}
{% block content %}

<main>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img
              class="img-fluid"
              alt="Responsive image"
              src="{{ product.image.url }}"
            />
            <div class="card-body">
              <p class="card-text">
                <a
                  class="text-dark text-decoration-none"
                  href="{{ product.get_absolute_url }}"
                  >{{ product.title }}</a
                >
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/store/products/detail.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock title %}
{% block content %}

<div class="container">
  <main class="pt-5">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{ product.image.url }}"
        />
      </div>
      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p><span class="lead">{{ product.author }}</span> (Author)</p>
        <p>{{ product.description|slice:":355" }}...</p>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Paperback</div>
              <div class="col-6 text-end">
                <span class="h4 fw-bold">£{{ product.price }}</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <label for="select">Qty</label>
                <select id="select">
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
              </div>
              <div class="col-6 text-end">
                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-primary btn-sm">
                  Add to basket
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}